### ISSUE TITLE
[Feat] 그룹 수정 취소 시 라우팅

### ISSUE THREAD

**Issue by ldcumg** [ldcumg/SnapRoad#232]
## 기존 방식

![GIFMaker_me](https://github.com/user-attachments/assets/fcdae7fa-689c-45b8-a1fb-6affd4459c04)

**Comment by yuna-c** [comment]
그게 더 좋을 것 같아요

**Comment by escape-engineering** [comment]
뒤로가기처리로 변경했습니다 #233
